sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true
      ROS_DISTRO="indigo"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      ADDITIONAL_DEBS="ros-indigo-image-transport ros-indigo-camera-info-manager ros-indigo-cv-bridge ros-indigo-gazebo7-ros ros-indigo-gazebo7-ros-pkgs ros-indigo-gazebo7-plugins"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
