sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true
      ROS_DISTRO="indigo"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      ADDITIONAL_DEBS="ros-indigo-image-transport ros-indigo-camera-info-manager ros-indigo-cv-bridge ros-indigo-gazebo7-ros-pkgs"
    - USE_DEB=true
      ROS_DISTRO="jade"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      ADDITIONAL_DEBS="ros-jade-image-transport ros-jade-camera-info-manager ros-jade-cv-bridge"
    - USE_DEB=true
      ROS_DISTRO="kinetic"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      ADDITIONAL_DEBS="ros-kinetic-image-transport ros-kinetic-camera-info-manager ros-kinetic-cv-bridge"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
script:
  - source .ci_config/travis.sh
  - source .travis.sh
